/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyReviewRouteImport } from './routes/weekly-review'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AiManagerRouteImport } from './routes/ai-manager'
import { Route as IndexRouteImport } from './routes/index'

const WeeklyReviewRoute = WeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiManagerRoute = AiManagerRouteImport.update({
  id: '/ai-manager',
  path: '/ai-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-manager': typeof AiManagerRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organizations': typeof OrganizationsRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-manager': typeof AiManagerRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organizations': typeof OrganizationsRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-manager': typeof AiManagerRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/events': typeof EventsRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organizations': typeof OrganizationsRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-review': typeof WeeklyReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-manager'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/events'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/opportunities'
    | '/organizations'
    | '/outreach'
    | '/settings'
    | '/tasks'
    | '/weekly-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-manager'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/events'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/opportunities'
    | '/organizations'
    | '/outreach'
    | '/settings'
    | '/tasks'
    | '/weekly-review'
  id:
    | '__root__'
    | '/'
    | '/ai-manager'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/events'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/opportunities'
    | '/organizations'
    | '/outreach'
    | '/settings'
    | '/tasks'
    | '/weekly-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiManagerRoute: typeof AiManagerRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EventsRoute: typeof EventsRoute
  InteractionsRoute: typeof InteractionsRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OrganizationsRoute: typeof OrganizationsRoute
  OutreachRoute: typeof OutreachRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WeeklyReviewRoute: typeof WeeklyReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-review': {
      id: '/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof WeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-manager': {
      id: '/ai-manager'
      path: '/ai-manager'
      fullPath: '/ai-manager'
      preLoaderRoute: typeof AiManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiManagerRoute: AiManagerRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EventsRoute: EventsRoute,
  InteractionsRoute: InteractionsRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OrganizationsRoute: OrganizationsRoute,
  OutreachRoute: OutreachRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WeeklyReviewRoute: WeeklyReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
